# Copier en inventory.ini et renseigner l adresse de la VM.
# inventory.ini n est pas versionne.
[enervision]
vm ansible_host=A_RENSEIGNER ansible_user=A_RENSEIGNER

[enervision:vars]
ansible_python_interpreter=/usr/bin/python3
