"""schema initial du contrat de donnees

Revision ID: 20260902_0001
Revises:
Create Date: 2026-09-02 15:00:05.968849

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260902_0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_quality_daily",
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("expected_points", sa.Integer(), nullable=False),
        sa.Column("received_points", sa.Integer(), nullable=False),
        sa.Column("missing_points", sa.Integer(), nullable=False),
        sa.Column("null_points", sa.Integer(), nullable=False),
        sa.Column("imputed_points", sa.Integer(), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("site_id", "day"),
        sa.UniqueConstraint("site_id", "day", name="uq_data_quality_daily_site_day"),
    )
    op.create_table(
        "etl_runs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("rows_read", sa.Integer(), nullable=False),
        sa.Column("rows_written", sa.Integer(), nullable=False),
        sa.Column("rows_imputed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'partial', 'failed')", name="ck_etl_runs_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "predictions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("predicted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("target_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_minutes", sa.Integer(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("model_version", sa.String(), nullable=False),
        sa.Column("predicted_kwh", sa.Float(), nullable=False),
        sa.Column("actual_kwh", sa.Float(), nullable=True),
        sa.Column(
            "absolute_error",
            sa.Float(),
            sa.Computed(
                "CASE WHEN actual_kwh IS NULL THEN NULL ELSE abs(predicted_kwh - actual_kwh) END",
            ),
            nullable=True,
        ),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "site_id",
            "target_at",
            "model_version",
            "horizon_minutes",
            name="uq_predictions_site_target_model_horizon",
        ),
    )
    op.create_index(op.f("ix_predictions_site_id"), "predictions", ["site_id"], unique=False)
    op.create_index(op.f("ix_predictions_target_at"), "predictions", ["target_at"], unique=False)
    op.create_table(
        "readings",
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumption_kwh", sa.Float(), nullable=True),
        sa.Column("consumption_kwh_raw", sa.Float(), nullable=True),
        sa.Column("is_imputed", sa.Boolean(), nullable=False),
        sa.Column("imputation_method", sa.String(), nullable=True),
        sa.Column("temperature_celsius", sa.Float(), nullable=True),
        sa.Column("humidity_percent", sa.Float(), nullable=True),
        sa.Column("data_quality", sa.String(), nullable=False),
        sa.Column("null_reasons", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "data_quality IN ('good', 'partial', 'degraded', 'critical')",
            name="ck_readings_data_quality",
        ),
        sa.PrimaryKeyConstraint("site_id", "measured_at"),
        sa.UniqueConstraint("site_id", "measured_at", name="uq_readings_site_measured"),
    )
    op.create_index(op.f("ix_readings_measured_at"), "readings", ["measured_at"], unique=False)
    op.create_index(op.f("ix_readings_site_id"), "readings", ["site_id"], unique=False)
    op.create_table(
        "sensor_status",
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("sensor", sa.String(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("failing_until", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "sensor IN ('consumption', 'electrical', 'temperature', 'humidity', 'network')",
            name="ck_sensor_status_sensor",
        ),
        sa.CheckConstraint("status IN ('ok', 'failing')", name="ck_sensor_status_status"),
        sa.PrimaryKeyConstraint("site_id", "sensor", "observed_at"),
        sa.UniqueConstraint(
            "site_id", "sensor", "observed_at", name="uq_sensor_status_site_sensor_observed"
        ),
    )
    op.create_table(
        "sites",
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("site_type", sa.String(), nullable=False),
        sa.Column("site_name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("capacity_kw", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status IN ('active', 'inactive')", name="ck_sites_status"),
        sa.PrimaryKeyConstraint("site_id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('viewer', 'operator', 'admin')", name="ck_users_role"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "alerts",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("site_id", sa.String(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("threshold_value", sa.Float(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("acknowledged_by", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "severity IN ('low', 'medium', 'high', 'critical')", name="ck_alerts_severity"
        ),
        sa.CheckConstraint("status IN ('open', 'acknowledged', 'closed')", name="ck_alerts_status"),
        sa.CheckConstraint(
            "type IN ('spike', 'threshold', 'anomaly', 'outage', 'sensor')", name="ck_alerts_type"
        ),
        sa.ForeignKeyConstraint(["acknowledged_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("site_id", "type", "detected_at", name="uq_alerts_site_type_detected"),
    )
    op.create_index(op.f("ix_alerts_detected_at"), "alerts", ["detected_at"], unique=False)
    op.create_index(op.f("ix_alerts_site_id"), "alerts", ["site_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_alerts_site_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_detected_at"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("sites")
    op.drop_table("sensor_status")
    op.drop_index(op.f("ix_readings_site_id"), table_name="readings")
    op.drop_index(op.f("ix_readings_measured_at"), table_name="readings")
    op.drop_table("readings")
    op.drop_index(op.f("ix_predictions_target_at"), table_name="predictions")
    op.drop_index(op.f("ix_predictions_site_id"), table_name="predictions")
    op.drop_table("predictions")
    op.drop_table("etl_runs")
    op.drop_table("data_quality_daily")
    # ### end Alembic commands ###
